name: CI
on:
  - push
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18.x
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        run: yarn install
      - name: Run zest unit tests
        run: npx baldrick-broth test spec
      - name: Run pest integration tests
        run: npx baldrick-broth test pest
      - name: Build
        run: yarn build
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Pest 
          path: report/*.pest.mocha.json
          reporter: mocha-json
